### PR TITLE
Feature/cele 32 iteration3

### PR DESCRIPTION
**Pull request by afonsobspinto**
closes iteration 3 of https://metacell.atlassian.net/browse/CELE-32

See the issue card for more details on what was done

### CODE REVIEW

**Comment by afonsobspinto** [comment]
Please be aware that this is still an open question:
https://metacell.atlassian.net/browse/CELE-32?focusedCommentId=15200

**Comment by aranega** [comment]
There is a small issue with this scenario `AIY, ASEL, ASE` only asking to display the neuron class, `AIY` and `ASE` should only display in the 2D graph, currently `ASEL` and `ASER` are also displaying.

**Comment by afonsobspinto** [comment]
Thanks. Just fixed that. Here are some of the cases I tested:

Case 1:
image
image

Case 2:
image
image

Case 3:
image
image

**Review by ddelpiano — APPROVED** [review]

**Comment by ddelpiano** [comment]
@aranega could you please allocate some time to review this so that we can merge it today and start testing it? thanks!

**Comment by ddelpiano** [comment]
> Please be aware that this is still an open question: [metacell.atlassian.net/browse/CELE-32?focusedCommentId=15200](https://metacell.atlassian.net/browse/CELE-32?focusedCommentId=15200)

This is a problem existing in their current implementation and so it should not impact the delivery of this task, in fairness we can address that in a separate task after we have a chat with the about it. Thanks for raising it @afonsobspinto

**Review by aranega — APPROVED** [review]
Thanks for the last fixes @afonsobspinto :)! Looks good to me!

@ddelpiano The PR is approved also on my side.

**Pull request merged**
