### PR TITLE
CELE-53 Add sharing URL to save/restore the global context

### PR DESCRIPTION
**Pull request by aranega**
Closes CELE-53 (at least a first version)

https://github.com/user-attachments/assets/bd0d4cd7-d084-4954-9715-71885559ddaa

### CODE REVIEW

**Review by afonsobspinto — APPROVED** [review]

**Review by afonsobspinto — CHANGES_REQUESTED** [review]
Looks good. One small detail, I believe we are always adding the default nodes no matter what, which sounds incorrect to me:

https://github.com/user-attachments/assets/ea487c75-7645-4f81-8bed-902eb19e43f6

**Comment by aranega** [comment]
@afonsobspinto I can fix partially the problem, but even if I deactivate the neuron in the left bar, it remains visible in the 2D graph. The problem comes mainly from the way the visibility is tackled in the global context and is handled in the 2D graph. We need to change this first, and it will be fixed by side-effect for the save/restore.

@ddelpiano I would prefer to have a new card for this refactoring about the neuron visibility. This is a significative refactoring and if we are including in this PR, I'm afraid it will add more conflicts and pain later to include it.

**Comment by aranega** [comment]
@afonsobspinto @ddelpiano I made a PR (#41) that changes the way the visibility by neurons is handled. This is now compatible with the global context and should fix the issue observed by @afonsobspinto .

**Review by afonsobspinto — APPROVED** [review]

**Comment by aranega** [comment]
@ddelpiano @afonsobspinto This PR now points on #40, so #40 should be merged before this PR

**Pull request merged**
